### ISSUE TITLE
Local DTG Model Support

### ISSUE THREAD

**Issue by KirariSpark** [huchenlei/ComfyUI_DanTagGen#10]
I can't assess huggingface (because of my region). Does this addon support local dtg model? so I can use local cached model downloaded from a mirror site.
I tried to edit `dan_tag_gen.py` but didn't work:
```python
MODEL_PATHS = [
    "KBlueLeaf/DanTagGen-alpha",
    "KBlueLeaf/DanTagGen-beta",
    "KBlueLeaf/DanTagGen-delta",
    "KBlueLeaf/DanTagGen-delta-rev2",
    "models\ggml-model-Q8_0.gguf",
    # I also tried ".\models\ggml-model-Q8_0.gguf", "models/ggml-model-Q8_0.gguf", "./models/ggml-model-Q8_0.gguf" and "C:\AI\StableDiffusion\Stable Diffusion ComfyUI Aki V1.2\custom_nodes\ComfyUI_DanTagGen\models\ggml-model-Q8_0.gguf"
]
```
I am using windows btw.

**Comment by XJF2332** [comment]
maybe I used the wrong format🤔
(sorry about my poor python level)

**Comment by KirariSpark** [comment]
maybe i used a wrong format🤔
(sorry about my poor python)
(and it's my first issue so I closed it by mistake😢)

**Comment by KirariSpark** [comment]
Problem solved.
Actually, you should input the path of the folder containing `config.json`, not the path of the `.gguf` file.
That is, you should download `KBlueLeaf/DanTagGen-delta-rev2` (or other models) and place them in a new folder under `comfyui\models`.
Additionally, it is not necessary to download the `.gguf` model, but the `.safetensors` model must be downloaded.
